import React from "react";
import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/header";
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
import {Poppins} from "next/font/google";

// In layout.tsx
import 'swiper/css';
import 'swiper/css/pagination';
import 'swiper/css/navigation';
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';

config.autoAddCss = false;

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});

export const metadata: Metadata = {
  title: "Governor Initiative",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${poppins.className}`}>
      <body
        className={`${poppins.variable} antialiased`}
      >
              <Header/>

        {children}
      </body>
    </html>
  );
}
